version: "3"
services:
  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
  
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongo/
  
  volumes:
    mongo-data
